"""OAuth 2.1 Authorization Server provider for the Knowledge Server (M2).

Implements the mcp SDK's OAuthAuthorizationServerProvider protocol, backed by:

  - ks-auth.db (SQLite)   : client registrations (DCR), pending authorizations,
                            authorization codes, refresh tokens
  - ks-secret.json        : scrypt passphrase hash + HS256 JWT signing key
                            (generated by `python -m ks.setpass`)

Design decisions (build log v0.5, session 2026-07-15):
  - Decision 14: auth state in a separate SQLite file, ks-auth.db
  - Decision 15: /authorize gated by a pre-shared passphrase (consent form)
  - Fork A1: passphrase hashed with stdlib hashlib.scrypt, constant-time compare
  - Fork B2: access tokens are HS256 JWTs (stateless verify, no DB read on the
             hot path); refresh tokens and auth codes remain opaque + DB-stored.
             Known tradeoff: revocation of a live access token is not possible;
             bounded by ACCESS_TOKEN_TTL_S. Revocation applies to refresh tokens.
  - Fork C2: secrets live in ks-secret.json (mode 600), outside git and outside
             config.py

Flow:
  1. Claude registers via DCR (/register) -> row in `clients`
  2. SDK /authorize handler calls KSAuthProvider.authorize() -> we park the
     request in `pending_auth` and redirect the browser to /consent?txn=...
  3. GET /consent serves the passphrase form; POST /consent verifies scrypt,
     mints a single-use authorization code, 302s back to the client's
     redirect_uri with code + state
  4. SDK /token handler verifies PKCE, calls exchange_authorization_code() ->
     JWT access token + opaque rotating refresh token
"""

from __future__ import annotations

import asyncio
import base64
import hashlib
import hmac
import html
import json
import logging
import secrets
import sqlite3
import time

import jwt
from starlette.requests import Request
from starlette.responses import HTMLResponse, RedirectResponse, Response

from mcp.server.auth.provider import (
    AccessToken,
    AuthorizationCode,
    AuthorizationParams,
    OAuthAuthorizationServerProvider,
    RefreshToken,
    construct_redirect_uri,
)
from mcp.shared.auth import OAuthClientInformationFull, OAuthToken

from . import config

log = logging.getLogger("ks.auth")

JWT_ALG = "HS256"
MAX_CONSENT_ATTEMPTS = 5
FAILED_ATTEMPT_DELAY_S = 0.75

# ---------------------------------------------------------------------------
# Secrets (ks-secret.json)
# ---------------------------------------------------------------------------

_secrets_cache: dict | None = None


def _load_secrets() -> dict:
    """Load and cache ks-secret.json. Fails loudly if missing."""
    global _secrets_cache
    if _secrets_cache is None:
        try:
            with open(config.SECRET_PATH, "r", encoding="utf-8") as f:
                _secrets_cache = json.load(f)
        except FileNotFoundError:
            raise RuntimeError(
                f"{config.SECRET_PATH} not found. "
                "Run: uv run python -m ks.setpass"
            )
    return _secrets_cache


def _jwt_key() -> bytes:
    return base64.b64decode(_load_secrets()["jwt_key"])


def verify_passphrase(candidate: str) -> bool:
    """scrypt + constant-time compare against the stored hash (Fork A1)."""
    s = _load_secrets()["passphrase"]
    derived = hashlib.scrypt(
        candidate.encode("utf-8"),
        salt=base64.b64decode(s["salt"]),
        n=s["n"],
        r=s["r"],
        p=s["p"],
        dklen=32,
    )
    return hmac.compare_digest(derived, base64.b64decode(s["hash"]))


# ---------------------------------------------------------------------------
# ks-auth.db
# ---------------------------------------------------------------------------

_DDL = """
CREATE TABLE IF NOT EXISTS clients (
    client_id     TEXT PRIMARY KEY,
    info_json     TEXT NOT NULL,
    registered_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS pending_auth (
    txn         TEXT PRIMARY KEY,
    client_id   TEXT NOT NULL,
    params_json TEXT NOT NULL,
    attempts    INTEGER NOT NULL DEFAULT 0,
    expires_at  INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS auth_codes (
    code                TEXT PRIMARY KEY,
    client_id           TEXT NOT NULL,
    scopes_json         TEXT NOT NULL,
    code_challenge      TEXT NOT NULL,
    redirect_uri        TEXT NOT NULL,
    redirect_uri_explicit INTEGER NOT NULL,
    expires_at          INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS refresh_tokens (
    token       TEXT PRIMARY KEY,
    client_id   TEXT NOT NULL,
    scopes_json TEXT NOT NULL,
    expires_at  INTEGER NOT NULL,
    revoked     INTEGER NOT NULL DEFAULT 0
);
"""


def _db() -> sqlite3.Connection:
    conn = sqlite3.connect(config.AUTH_DB_PATH, timeout=10)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


def init_auth_db() -> None:
    """Idempotent schema creation. Called once at server startup."""
    with _db() as conn:
        conn.executescript(_DDL)
    log.info("auth db ready at %s", config.AUTH_DB_PATH)


def cleanup_expired() -> None:
    """Purge expired transient rows. Called from the server's poller loop.

    Revoked/expired refresh tokens are retained for one extra day so that a
    late /revoke or /token call gets a clean 'invalid' rather than 'unknown'.
    """
    now = int(time.time())
    with _db() as conn:
        conn.execute("DELETE FROM pending_auth WHERE expires_at < ?", (now,))
        conn.execute("DELETE FROM auth_codes WHERE expires_at < ?", (now,))
        conn.execute(
            "DELETE FROM refresh_tokens WHERE expires_at < ? OR (revoked = 1 AND expires_at < ?)",
            (now - 86400, now),
        )


# ---------------------------------------------------------------------------
# JWT access tokens (Fork B2)
# ---------------------------------------------------------------------------

def _mint_access_token(client_id: str, scopes: list[str]) -> tuple[str, int]:
    now = int(time.time())
    exp = now + config.ACCESS_TOKEN_TTL_S
    token = jwt.encode(
        {
            "iss": config.ISSUER_URL,
            "aud": config.JWT_AUDIENCE,
            "sub": client_id,
            "jti": secrets.token_urlsafe(12),
            "iat": now,
            "exp": exp,
            "scope": " ".join(scopes),
        },
        _jwt_key(),
        algorithm=JWT_ALG,
    )
    return token, exp


def _mint_refresh_token(conn: sqlite3.Connection, client_id: str, scopes: list[str]) -> str:
    token = secrets.token_urlsafe(32)
    conn.execute(
        "INSERT INTO refresh_tokens (token, client_id, scopes_json, expires_at) VALUES (?, ?, ?, ?)",
        (token, client_id, json.dumps(scopes), int(time.time()) + config.REFRESH_TOKEN_TTL_S),
    )
    return token


def _token_response(conn: sqlite3.Connection, client_id: str, scopes: list[str]) -> OAuthToken:
    access, _exp = _mint_access_token(client_id, scopes)
    refresh = _mint_refresh_token(conn, client_id, scopes)
    return OAuthToken(
        access_token=access,
        token_type="Bearer",
        expires_in=config.ACCESS_TOKEN_TTL_S,
        scope=" ".join(scopes) if scopes else None,
        refresh_token=refresh,
    )


# ---------------------------------------------------------------------------
# Provider
# ---------------------------------------------------------------------------

class KSAuthProvider(
    OAuthAuthorizationServerProvider[AuthorizationCode, RefreshToken, AccessToken]
):
    # -- clients (DCR) ------------------------------------------------------

    async def get_client(self, client_id: str) -> OAuthClientInformationFull | None:
        with _db() as conn:
            row = conn.execute(
                "SELECT info_json FROM clients WHERE client_id = ?", (client_id,)
            ).fetchone()
        if row is None:
            return None
        return OAuthClientInformationFull.model_validate_json(row["info_json"])

    async def register_client(self, client_info: OAuthClientInformationFull) -> None:
        with _db() as conn:
            conn.execute(
                "INSERT OR REPLACE INTO clients (client_id, info_json, registered_at) VALUES (?, ?, ?)",
                (client_info.client_id, client_info.model_dump_json(), int(time.time())),
            )
        log.info("DCR: registered client %s", client_info.client_id)

    # -- authorize -> consent hand-off --------------------------------------

    async def authorize(
        self, client: OAuthClientInformationFull, params: AuthorizationParams
    ) -> str:
        txn = secrets.token_urlsafe(24)
        payload = {
            "state": params.state,
            "scopes": params.scopes or [],
            "code_challenge": params.code_challenge,
            "redirect_uri": str(params.redirect_uri),
            "redirect_uri_provided_explicitly": params.redirect_uri_provided_explicitly,
        }
        with _db() as conn:
            conn.execute(
                "INSERT INTO pending_auth (txn, client_id, params_json, expires_at) VALUES (?, ?, ?, ?)",
                (txn, client.client_id, json.dumps(payload),
                 int(time.time()) + config.PENDING_AUTH_TTL_S),
            )
        return f"{config.ISSUER_URL}/consent?txn={txn}"

    # -- authorization codes -------------------------------------------------

    async def load_authorization_code(
        self, client: OAuthClientInformationFull, authorization_code: str
    ) -> AuthorizationCode | None:
        with _db() as conn:
            row = conn.execute(
                "SELECT * FROM auth_codes WHERE code = ?", (authorization_code,)
            ).fetchone()
        if row is None or row["client_id"] != client.client_id:
            return None
        if row["expires_at"] < time.time():
            return None
        return AuthorizationCode(
            code=row["code"],
            client_id=row["client_id"],
            scopes=json.loads(row["scopes_json"]),
            expires_at=float(row["expires_at"]),
            code_challenge=row["code_challenge"],
            redirect_uri=row["redirect_uri"],
            redirect_uri_provided_explicitly=bool(row["redirect_uri_explicit"]),
        )

    async def exchange_authorization_code(
        self, client: OAuthClientInformationFull, authorization_code: AuthorizationCode
    ) -> OAuthToken:
        with _db() as conn:
            cur = conn.execute(
                "DELETE FROM auth_codes WHERE code = ?", (authorization_code.code,)
            )
            if cur.rowcount == 0:
                raise ValueError("authorization code already redeemed")
            return _token_response(conn, client.client_id, authorization_code.scopes)

    # -- refresh tokens (opaque, rotating) -----------------------------------

    async def load_refresh_token(
        self, client: OAuthClientInformationFull, refresh_token: str
    ) -> RefreshToken | None:
        with _db() as conn:
            row = conn.execute(
                "SELECT * FROM refresh_tokens WHERE token = ?", (refresh_token,)
            ).fetchone()
        if row is None or row["client_id"] != client.client_id:
            return None
        if row["revoked"] or row["expires_at"] < time.time():
            return None
        return RefreshToken(
            token=row["token"],
            client_id=row["client_id"],
            scopes=json.loads(row["scopes_json"]),
            expires_at=int(row["expires_at"]),
        )

    async def exchange_refresh_token(
        self,
        client: OAuthClientInformationFull,
        refresh_token: RefreshToken,
        scopes: list[str],
    ) -> OAuthToken:
        granted = scopes or refresh_token.scopes
        with _db() as conn:
            conn.execute(
                "UPDATE refresh_tokens SET revoked = 1 WHERE token = ?",
                (refresh_token.token,),
            )
            return _token_response(conn, client.client_id, granted)

    # -- access tokens (JWT, stateless) --------------------------------------

    async def load_access_token(self, token: str) -> AccessToken | None:
        try:
            claims = jwt.decode(
                token,
                _jwt_key(),
                algorithms=[JWT_ALG],
                audience=config.JWT_AUDIENCE,
                issuer=config.ISSUER_URL,
            )
        except jwt.PyJWTError:
            return None
        scope = claims.get("scope", "")
        return AccessToken(
            token=token,
            client_id=claims["sub"],
            scopes=scope.split() if scope else [],
            expires_at=int(claims["exp"]),
        )

    # -- revocation -----------------------------------------------------------

    async def revoke_token(self, token: AccessToken | RefreshToken) -> None:
        if isinstance(token, RefreshToken):
            with _db() as conn:
                conn.execute(
                    "UPDATE refresh_tokens SET revoked = 1 WHERE token = ?",
                    (token.token,),
                )
            log.info("revoked refresh token for client %s", token.client_id)
        else:
            # Fork B2 accepted tradeoff: JWTs cannot be revoked server-side;
            # they expire within ACCESS_TOKEN_TTL_S.
            log.info(
                "revoke requested for JWT access token (client %s); "
                "no-op by design, expires within %ss",
                token.client_id, config.ACCESS_TOKEN_TTL_S,
            )


# ---------------------------------------------------------------------------
# /consent routes (Decision 15) — wired via @mcp.custom_route in server.py
# ---------------------------------------------------------------------------

_FORM_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Knowledge Server</title>
<style>
 body {{ font-family: -apple-system, system-ui, sans-serif; background:#111;
        color:#ddd; display:flex; justify-content:center; padding-top:12vh; }}
 form {{ background:#1c1c1e; padding:2rem; border-radius:12px; width:20rem; }}
 h1 {{ font-size:1.1rem; margin:0 0 1rem; }}
 input[type=password] {{ width:100%; box-sizing:border-box; padding:.6rem;
        border-radius:6px; border:1px solid #444; background:#000; color:#eee; }}
 button {{ margin-top:1rem; width:100%; padding:.6rem; border:0;
        border-radius:6px; background:#0a84ff; color:#fff; font-size:1rem; }}
 .err {{ color:#ff453a; font-size:.85rem; min-height:1.2em; margin-top:.5rem; }}
</style></head><body>
<form method="post" action="/consent">
  <h1>Knowledge Server &mdash; authorize connector</h1>
  <input type="hidden" name="txn" value="{txn}">
  <input type="password" name="passphrase" placeholder="Passphrase" autofocus autocomplete="off">
  <div class="err">{error}</div>
  <button type="submit">Authorize</button>
</form></body></html>"""


def _render_form(txn: str, error: str = "") -> HTMLResponse:
    return HTMLResponse(
        _FORM_TEMPLATE.format(txn=html.escape(txn), error=html.escape(error))
    )


def _load_pending(txn: str) -> sqlite3.Row | None:
    with _db() as conn:
        row = conn.execute(
            "SELECT * FROM pending_auth WHERE txn = ?", (txn,)
        ).fetchone()
    if row is None or row["expires_at"] < time.time():
        return None
    return row


async def consent_get(request: Request) -> Response:
    txn = request.query_params.get("txn", "")
    if not txn or _load_pending(txn) is None:
        return HTMLResponse("Authorization request expired or invalid. "
                            "Restart the connector flow.", status_code=400)
    return _render_form(txn)


async def consent_post(request: Request) -> Response:
    form = await request.form()
    txn = str(form.get("txn", ""))
    passphrase = str(form.get("passphrase", ""))

    row = _load_pending(txn)
    if row is None:
        return HTMLResponse("Authorization request expired or invalid. "
                            "Restart the connector flow.", status_code=400)

    if not verify_passphrase(passphrase):
        await asyncio.sleep(FAILED_ATTEMPT_DELAY_S)
        with _db() as conn:
            conn.execute(
                "UPDATE pending_auth SET attempts = attempts + 1 WHERE txn = ?", (txn,)
            )
            attempts = conn.execute(
                "SELECT attempts FROM pending_auth WHERE txn = ?", (txn,)
            ).fetchone()["attempts"]
            if attempts >= MAX_CONSENT_ATTEMPTS:
                conn.execute("DELETE FROM pending_auth WHERE txn = ?", (txn,))
                log.warning("consent: txn %s destroyed after %d failed attempts",
                            txn, attempts)
                return HTMLResponse("Too many attempts. Restart the connector flow.",
                                    status_code=403)
        log.warning("consent: bad passphrase, txn %s attempt %d", txn, attempts)
        return _render_form(txn, "Incorrect passphrase.")

    params = json.loads(row["params_json"])
    code = secrets.token_urlsafe(32)
    with _db() as conn:
        conn.execute("DELETE FROM pending_auth WHERE txn = ?", (txn,))
        conn.execute(
            "INSERT INTO auth_codes (code, client_id, scopes_json, code_challenge, "
            "redirect_uri, redirect_uri_explicit, expires_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (code, row["client_id"], json.dumps(params["scopes"]),
             params["code_challenge"], params["redirect_uri"],
             int(params["redirect_uri_provided_explicitly"]),
             int(time.time()) + config.AUTH_CODE_TTL_S),
        )
    log.info("consent: passphrase OK, code issued to client %s", row["client_id"])
    dest = construct_redirect_uri(
        params["redirect_uri"], code=code, state=params["state"]
    )
    return RedirectResponse(dest, status_code=302)
